apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.backend.name}}
  name: {{ .Values.backend.name}}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  {{- if .Values.backend.exporter }}
  - name: load
    protocol: TCP
    port: 3000
  {{- end }}
  selector:
    app: {{ .Values.backend.name }}
