apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: powerapp-backend
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        env:
        - name: MONGO_HOST
          value: {{ .Values.mongo.name }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      {{- if .Values.backend.exporter }}
      - image: phisco/exporter
        name: exporter
      {{- end }}
      restartPolicy: Always
