{{- if .Values.backend.autoscaler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: autoscaler
  template:
    metadata:
      labels:
        name: autoscaler
    spec:
      serviceAccountName: autoscaler
      containers:
      - image: {{ .Values.backend.autoscaler.image }}
        imagePullPolicy: Always
        name: autoscaler
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_NAME
          value: {{ .Values.backend.name }}
        - name: TARGET_SERVICE
          value: {{ .Values.backend.name }}
        - name: TARGET_PORT
          value: "3000"
        - name: MIN_REPLICAS
          value: {{ .Values.backend.autoscaler.min }}
        - name: MAX_REPLICAS
          value: {{ .Values.backend.autoscaler.max }}
        - name: SECONDS
          value: {{ .Values.backend.autoscaler.seconds }}
      restartPolicy: Always
{{- end }}
