apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mongo.name }}
  name: {{ .Values.mongo.name }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: {{ .Values.mongo.name }}
