apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.web.name }}
  name: {{ .Values.web.name }}
spec:
  ports:
  - name: "web"
    port: 80
    protocol: TCP
  selector:
    app: {{ .Values.web.name }}
