apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.web.name }}
  name: {{ .Values.web.name }}
spec:
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image }}
        env:
        - name: BACKEND_HOST
          value: {{ .Values.backend.name }}
        - name: COMPANY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.web.configMapName }}
              key: COMPANY
        - name: SOME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.web.secretName }}
              key: some-password
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always
