---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: autoscaler
rules:
- apiGroups: ["", "extensions", "apps", "extension/v1beta1"]
  resources: ["deployments"]
  verbs: ["get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: autoscaler
subjects:
- kind: ServiceAccount
  name: autoscaler
roleRef:
  kind: Role
  name: autoscaler
  apiGroup: rbac.authorization.k8s.io
