apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: powerapp-backend-service
  name: powerapp-backend-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: powerapp-backend
